//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musicistian
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicData
    {
        public string Artist { get; set; }
        public string Song { get; set; }
        public string Album { get; set; }
        public string Genre { get; set; }
        public Nullable<double> PlayCount { get; set; }
        public int ID { get; set; }
    }
}
